name: "CCIS2500 Spring 2017"   # CHANGE ME
baseurl: /spring-2017          # CHANGE ME
github_org_url: https://github.com/htc-ccis2500-spring2017 # CHANGE ME
github_org_name: "HTC CCIS2500 Spring 2017" # CHANGE ME

# The following properties should not need to change semester to semester.
markdown: kramdown
kramdown:
  hard_wrap: false
  input: GFM
  syntax_highlighter: rouge
mathjax: true
exclude: [morea]
morea_theme: spacelab
morea_navbar_items:
  #- Prerequisites
  - Modules
  - Outcomes
  - Readings
  - Experiences
  - Assessments
  - Schedule

gems:
  - jekyll-gist
  - jemoji

morea_course: CCIS 2500
morea_domain: http://htc-ccis2500.github.io/
morea_google_analytics_tracking_id: "UA-63189236-6"
googleCalendarApiKey: AIzaSyC6v2gy8gUv3Ra1wBeZHVB99SD0r1sHdjE
googleCalendarId: 'nvb9t6vbhk4gtp3jdpdfdb69l8@group.calendar.google.com'
